services:
    app:
        profiles: [ "disabled" ]

    mysql:
        ports:
            - 3306:3306

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
            - "1025:1025"
