services:
    app:
        profiles: [ "disabled" ]

    mysql:
        ports:
            - 13306:3306

    mailhog:
        image: mailhog/mailhog
        ports:
            - "18025:8025"
            - "11025:1025"
